title: Veronica-Victoria Art
email: mail@veronica-victoria.art
description: >-
  Veronica-Victoria Art
baseurl: ""
url: "//veronica-victoria.art"
twitter_username: vikiviart
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
